version: '3.8'

services:
  db:
    container_name: database
    image: postgres:16
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@1234
      POSTGRES_DB: cinema
    volumes:
      - db-postgres:/var/lib/postgresql/data
volumes:
  db-postgres: